version: '3.1'

services:

  api:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=60


  postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction_routines

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
  
  docs:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    environment:
      - SWAGGER_JSON=/docs/swagger.json
    volumes:
      - ./docs:/docs


volumes: 
  pgdata: