version: '3.1'

services:

  postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction_routines

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes: 
  pgdata: