version: '3.1'

services:

  postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction_routines
